import {useState} from "react";
import {ArrowRight,ChevronDown,Menu,X,Factory,Gauge,Ruler,Cog,Boxes,Mail,Phone,MapPin,Send,CheckCircle2} from "lucide-react";

const hero="https://images.unsplash.com/photo-1565439374674-9f4bcb9b4b3c?auto=format&fit=crop&w=2200&q=85";
const cnc="https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1400&q=85";
const quality = "/assets/metrologia.jpg";

const services=[
{icon:Cog,n:"01",title:"Usinagem CNC",text:"Produção de peças com precisão, rastreabilidade e controle de processo para aplicações industriais exigentes."},
{icon:Factory,n:"02",title:"Desenvolvimento",text:"Dispositivos, ferramentas e soluções de processo desenvolvidos de acordo com a necessidade do seu projeto."},
{icon:Ruler,n:"03",title:"Metrologia & Qualidade",text:"Inspeção dimensional e controle rigoroso para garantir que cada componente esteja dentro das especificações."},
{icon:Gauge,n:"04",title:"Produção Seriada",text:"Estrutura preparada para transformar pequenos lotes em produção consistente, eficiente e escalável."}];

const videos=[
  {title:"Sobre A MARKS",tag:"PROCESSO",poster:cnc,file:"/videos/sobre.mp4"},
  {title:"Usinagem",tag:"USINAGEM",poster:quality,file:"/videos/controle-qualidade.mp4"},
  {title:"Dentro da fábrica",tag:"ESTRUTURA",poster:hero,file:"/videos/dentro-da-fabrica.mp4"},
];

const machines=[
["CENTRO CNC HORIZONTAL","Alta produtividade e troca rápida de ferramentas","DOOSAN / MORI SEIKI /"],
["CENTRO CNC VERTICAL","Flexibilidade para diferentes geometrias e operações","BROTHER"],
["MEDIÇÃO TRIDIMENSIONAL","Controle dimensional de alta precisão","MITUTOYO"],
["PRESET DE FERRAMENTAS","Setup preciso e redução do tempo de preparação","ZOLLER"]];

function Header(){const[open,setOpen]=useState(false);const links=[["Início","#inicio"],["Serviços","#servicos"],["Estrutura","#estrutura"],["Vídeos","#videos"],["Qualidade","#qualidade"],["Sobre","#sobre"],["Contato","#contato"]];return <header className="fixed top-0 z-50 w-full border-b border-white/10 bg-[#080a0d]/85 backdrop-blur-xl"><div className="container-page flex h-20 items-center justify-between"><a href="#inicio" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center border-2 border-[#f2b233] text-lg font-black text-[#f2b233]">M</span><span><strong className="display block text-2xl leading-none tracking-[.12em]">MARKS</strong><small className="text-[8px] font-bold tracking-[.4em] text-zinc-500">INDUSTRIAL</small></span></a><nav className="hidden items-center gap-7 lg:flex">{links.map(([t,h])=><a key={t} href={h} className="text-[11px] font-semibold uppercase tracking-[.12em] text-zinc-300 transition hover:text-[#f2b233]">{t}</a>)}</nav><a href="#contato" className="hidden items-center gap-2 bg-[#f2b233] px-5 py-3 text-[10px] font-extrabold uppercase tracking-wider text-black hover:bg-[#ffc650] lg:flex">Solicitar orçamento <ArrowRight size={14}/></a><button onClick={()=>setOpen(!open)} className="p-2 lg:hidden">{open?<X/>:<Menu/>}</button></div>{open&&<div className="border-t border-white/10 bg-[#0a0d11] p-5 lg:hidden">{links.map(([t,h])=><a key={t} href={h} onClick={()=>setOpen(false)} className="block border-b border-white/5 py-4 text-xs font-bold uppercase tracking-widest">{t}</a>)}</div>}</header>}

function Hero(){return <section id="inicio" className="relative min-h-[760px] overflow-hidden pt-20"><img src={hero} className="absolute inset-0 h-full w-full object-cover" alt="Máquina industrial CNC"/><div className="image-overlay absolute inset-0"/><div className="container-page relative flex min-h-[680px] items-end pb-24"><div className="max-w-3xl"><div className="mb-6 flex items-center gap-3 text-[10px] font-bold uppercase tracking-[.3em] text-[#f2b233]"><span className="h-px w-12 bg-[#f2b233]"/>Usinagem CNC de precisão</div><h1 className="display text-7xl font-bold uppercase leading-[.82] sm:text-8xl lg:text-[9.5rem]">Precisão<br/><span className="text-[#f2b233]">em cada</span><br/>detalhe.</h1><p className="mt-8 max-w-xl text-sm leading-7 text-zinc-300 sm:text-base">Engenharia, tecnologia e experiência para transformar projetos complexos em componentes de alta precisão.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#contato" className="flex items-center gap-3 bg-[#f2b233] px-6 py-4 text-[10px] font-black uppercase tracking-wider text-black hover:bg-[#ffc650]">Solicitar orçamento <ArrowRight size={15}/></a><a href="#servicos" className="flex items-center gap-3 border border-white/20 bg-black/20 px-6 py-4 text-[10px] font-black uppercase tracking-wider text-white hover:border-[#f2b233]">Conheça nossa estrutura</a></div></div></div><a href="#servicos" className="absolute bottom-7 left-1/2 hidden -translate-x-1/2 flex-col items-center gap-2 text-[8px] uppercase tracking-[.3em] text-zinc-400 sm:flex">Scroll <ChevronDown size={14}/></a></section>}

function Services(){return <section id="servicos" className="py-24"><div className="container-page"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-[10px] font-bold uppercase tracking-[.3em] text-[#f2b233]">O que fazemos</p><h2 className="display mt-3 text-6xl font-bold uppercase leading-none">Soluções<br/><span className="text-zinc-500">industriais.</span></h2><p className="mt-6 max-w-md text-sm leading-7 text-zinc-500">Do desenvolvimento do processo à inspeção final, conectamos engenharia, produção e qualidade em um único fluxo.</p></div><div className="grid gap-px overflow-hidden border border-white/10 bg-white/10 sm:grid-cols-2">{services.map(s=><article key={s.n} className="reveal border border-transparent bg-[#0b0e12] p-7"><div className="flex justify-between"><s.icon className="text-[#f2b233]" size={28} strokeWidth={1.5}/><span className="display text-3xl text-zinc-700">{s.n}</span></div><h3 className="display mt-12 text-3xl font-bold uppercase">{s.title}</h3><p className="mt-3 text-xs leading-6 text-zinc-500">{s.text}</p></article>)}</div></div></div></section>}

function Numbers(){return <section className="border-y border-white/10 bg-[#0c1015] py-10"><div className="container-page grid grid-cols-2 gap-8 lg:grid-cols-4">{[["37+","ANOS DE EXPERIÊNCIA"],["26","MÁQUINAS CNC"],["2.500","M² DE ESTRUTURA"],["100%","FOCO EM QUALIDADE"]].map(([n,l])=><div key={l} className="border-l border-[#f2b233]/50 pl-5"><strong className="display text-5xl font-bold sm:text-6xl">{n}</strong><p className="mt-1 text-[9px] font-bold tracking-[.2em] text-zinc-500">{l}</p></div>)}</div></section>}

function Structure(){return <section id="estrutura" className="py-24"><div className="container-page"><div className="mb-10 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><h2 className="display mt-3 text-6xl font-bold uppercase leading-none">Tecnologia<br/><span className="text-zinc-500">que produz.</span></h2></div><p className="max-w-md text-xs leading-6 text-zinc-500">Equipamentos de alto desempenho para entregar produtividade, repetibilidade e controle.</p></div><div className="grid gap-3 lg:grid-cols-[1.35fr_.65fr]"><div className="relative min-h-[500px] overflow-hidden"><img src={cnc} alt="Centro de usinagem CNC" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/20 to-transparent"/><div className="absolute bottom-7 left-7"><p className="text-[9px] font-bold uppercase tracking-[.25em] text-[#f2b233]">01 / Destaque</p><h3 className="display mt-2 text-4xl font-bold uppercase">Centros CNC<br/>de alta performance</h3></div></div><div className="grid gap-px bg-white/10">{machines.map(([t,d,b],i)=><article key={t} className="reveal border border-transparent bg-[#0c1015] p-6"><div className="flex justify-between"><span className="text-[9px] font-bold text-[#f2b233]">0{i+1}</span><Boxes size={17} className="text-zinc-600"/></div><h3 className="display mt-5 text-2xl font-bold uppercase">{t}</h3><p className="mt-2 text-[11px] leading-5 text-zinc-500">{d}</p><p className="mt-4 text-[8px] font-bold tracking-[.18em] text-zinc-600">{b}</p></article>)}</div></div></div></section>}

function Videos(){
  const [active,setActive]=useState<string|null>(null);
  return <section id="videos" className="bg-[#080a0d] py-24">
    <div className="container-page">
      <div className="mb-10 flex flex-col justify-between gap-5 md:flex-row md:items-end">
        <div>
          <p className="text-[10px] font-bold uppercase tracking-[.3em] text-[#f2b233]">Por dentro da operação</p>
          <h2 className="display mt-3 text-6xl font-bold uppercase leading-none">Tecnologia<br/><span className="text-zinc-500">em movimento.</span></h2>
        </div>
        <p className="max-w-md text-xs leading-6 text-zinc-500">Veja nossas máquinas, processos e equipe em ação. Troque os vídeos demonstrativos pelos registros reais da empresa.</p>
      </div>
      <div className="grid gap-4 lg:grid-cols-3">
        {videos.map((v,i)=><article key={v.title} className="reveal group overflow-hidden border border-white/10 bg-[#0c1015]">
          <button type="button" onClick={()=>setActive(v.file)} className="relative block aspect-video w-full overflow-hidden text-left">
            <video src={v.file} poster={v.poster} autoPlay muted loop playsInline aria-label={v.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/>
            <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/10 to-black/10"/>
            <div className="absolute left-5 top-5 text-[8px] font-bold tracking-[.25em] text-[#f2b233]">0{i+1} / {v.tag}</div>
            <span className="absolute left-1/2 top-1/2 grid h-14 w-14 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border border-white/50 bg-[#f2b233] text-black shadow-2xl transition group-hover:scale-110">▶</span>
          </button>
          <div className="p-5"><h3 className="display text-2xl font-bold uppercase">{v.title}</h3><p className="mt-2 text-[10px] text-zinc-600">Clique para assistir</p></div>
        </article>)}
      </div>
    </div>
    {active&&<div className="fixed inset-0 z-[80] grid place-items-center bg-black/90 p-5 backdrop-blur-sm" onClick={()=>setActive(null)}>
      <div className="relative w-full max-w-5xl" onClick={e=>e.stopPropagation()}>
        <button type="button" onClick={()=>setActive(null)} className="absolute -right-2 -top-12 text-sm font-bold text-white">FECHAR ×</button>
        <video src={active} controls autoPlay className="max-h-[80vh] w-full bg-black" />
        <p className="mt-3 text-[9px] uppercase tracking-[.2em] text-zinc-500">Vídeo da operação industrial</p>
      </div>
    </div>}
  </section>
}

function Quality(){return <section id="qualidade" className="bg-[#0c1015] py-24"><div className="container-page grid items-center gap-12 lg:grid-cols-2"><div><div className="relative overflow-hidden"><img src={quality} alt="Controle de qualidade industrial" className="h-[500px] w-full object-cover grayscale"/><div className="absolute bottom-5 left-5 border border-[#f2b233]/40 bg-black/70 px-5 py-4"><p className="text-[8px] font-bold tracking-[.2em] text-[#f2b233]">CONTROLE DIMENSIONAL</p><p className="mt-1 text-xs text-zinc-300">Precisão validada antes da entrega.</p></div></div></div><div><p className="text-[10px] font-bold uppercase tracking-[.3em] text-[#f2b233]">Qualidade</p><h2 className="display mt-3 text-6xl font-bold uppercase leading-none">Qualidade<br/><span className="text-zinc-500">não é etapa.</span></h2><p className="mt-7 text-sm leading-7 text-zinc-400">É processo. Cada peça passa por critérios definidos para assegurar conformidade, repetibilidade e confiança em cada lote.</p><div className="mt-8 space-y-4">{["Inspeção dimensional","Controle de processo","Rastreabilidade","Equipe técnica especializada"].map(x=><div key={x} className="flex items-center gap-3 border-b border-white/10 pb-4 text-xs font-semibold"><CheckCircle2 size={17} className="text-[#f2b233]"/>{x}</div>)}</div></div></div></section>}

function About(){return <section id="sobre" className="grid-tech py-24"><div className="container-page grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-[10px] font-bold uppercase tracking-[.3em] text-[#f2b233]">Nossa história</p><h2 className="display mt-3 text-6xl font-bold uppercase leading-none">Experiência<br/><span className="text-zinc-500">que evolui.</span></h2></div><div><p className="text-lg leading-8 text-zinc-300">Uma empresa industrial precisa fazer mais do que usinar. Precisa entender o desafio, desenvolver o processo certo e entregar consistência.</p><p className="mt-5 text-sm leading-7 text-zinc-500">Experiência prática e evolução tecnológica se unem para atender projetos de diferentes níveis de complexidade com agilidade e controle.</p><div className="mt-10 grid gap-4 border-t border-white/10 pt-8 sm:grid-cols-3">{[["01","Engenharia"],["02","Produção"],["03","Qualidade"]].map(([n,t])=><div key={n}><span className="text-[9px] text-[#f2b233]">{n}</span><p className="display mt-2 text-2xl font-bold uppercase">{t}</p></div>)}</div></div></div></section>}

function Contact(){const[sent,setSent]=useState(false);return <section id="contato" className="border-t border-white/10 py-24"><div className="container-page grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-[10px] font-bold uppercase tracking-[.3em] text-[#f2b233]">Vamos conversar</p><h2 className="display mt-3 text-7xl font-bold uppercase leading-[.85]">Seu projeto.<br/><span className="text-[#f2b233]">Nossa precisão.</span></h2><p className="mt-7 max-w-md text-sm leading-6 text-zinc-500">Envie os dados do projeto e nossa equipe retorna para avaliar a melhor solução.</p><div className="mt-8 space-y-4 text-xs text-zinc-400"><p className="flex gap-3"><Mail size={16} className="text-[#f2b233]"/> atendimento@marks.ind.br</p><p className="flex gap-3"><Phone size={16} className="text-[#f2b233]"/> (11) 4546-8770</p><p className="flex gap-3"><MapPin size={16} className="text-[#f2b233]"/> Mauá — São Paulo, Brasil</p></div></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent?<div className="grid min-h-[430px] place-items-center border border-[#f2b233]/30 bg-[#0d1116] text-center"><div><CheckCircle2 size={50} className="mx-auto text-[#f2b233]"/><h3 className="display mt-5 text-4xl font-bold uppercase">Mensagem enviada.</h3><p className="mt-2 text-xs text-zinc-500">Conecte este formulário ao backend para receber os dados.</p></div></div>:<div className="grid gap-3"><div className="grid gap-3 sm:grid-cols-2"><input required className="input-dark px-4 py-4 text-xs" placeholder="Nome"/><input required type="email" className="input-dark px-4 py-4 text-xs" placeholder="E-mail"/></div><input className="input-dark px-4 py-4 text-xs" placeholder="WhatsApp"/><div className="grid gap-3 sm:grid-cols-2"><input className="input-dark px-4 py-4 text-xs" placeholder="Tipo de peça / serviço"/><input className="input-dark px-4 py-4 text-xs" placeholder="Quantidade"/></div><textarea className="input-dark min-h-36 resize-none px-4 py-4 text-xs" placeholder="Conte um pouco sobre o projeto..."/><label className="flex cursor-pointer items-center gap-3 border border-dashed border-white/10 p-4 text-[10px] text-zinc-500"><input type="file"/> Anexe desenho técnico (PDF, STEP ou DWG)</label><button className="flex items-center justify-center gap-3 bg-[#f2b233] px-6 py-4 text-[10px] font-black uppercase tracking-wider text-black hover:bg-[#ffc650]">Enviar projeto <Send size={14}/></button></div>}</form></div></section>}

function Footer(){return <footer className="border-t border-white/10 py-8"><div className="container-page flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><div className="display text-2xl font-bold tracking-widest">MARKS</div><p className="text-[8px] tracking-[.3em] text-zinc-600">INDUSTRIAL PRECISION</p></div><p className="text-[9px] text-zinc-600">© 2026 Marks Industrial.</p><div className="text-[9px] font-bold uppercase tracking-widest text-zinc-500">CNC • ENGINEERING • QUALITY</div></div></footer>}

export default function App(){return <><Header/><main><Hero/><Services/><Numbers/><Structure/><Videos/><Quality/><About/><Contact/></main><Footer/></>}
